### PR TITLE
feat(docs): Add MailerSend

### PR DESCRIPTION
**Pull request by opheus2**
Add MailerSend as an additional email service provider using their NodeJS SDK.

This should close this issue https://github.com/resendlabs/react-email/issues/444

### CODE REVIEW

**Comment by bukinoshita** [comment]
Can you add the `MailerSend` [here](https://github.com/resendlabs/react-email/blob/main/apps/docs/introduction.mdx#integrations) and [here](https://github.com/resendlabs/react-email/blob/main/apps/docs/mint.json#L94) after AWS SES?

**Comment by bukinoshita** [comment]
@opheus2 Any update on this?

**Comment by opheus2** [comment]
> @opheus2 Any update on this?

done

**Comment by bukinoshita** [comment]
Thanks!

**Pull request merged**
