### PR TITLE
feat(Font): Implemented web fonts

### LINKED ISSUE #54: Add support for web fonts
References:
* https://www.cerberusemail.com/components#h-H3_8
* https://www.caniemail.com/features/css-at-font-face/
* https://maizzle.com/docs/examples/google-fonts#font-face

### PR DESCRIPTION
**Pull request by bastiaanv**
First implementation of Web Fonts. Always open for feedback/improvements

Sources:
- https://www.litmus.com/blog/the-ultimate-guide-to-web-fonts/
- https://www.caniemail.com/features/css-at-font-face/

Closes #54

### CODE REVIEW

**Review by davidhollenbeckx — CHANGES_REQUESTED** [review]
dropped the component into my project since I needed this, thank you!

I updated line 46 font.tsx, 

`src: url(${webFont}) format('${webFont.format}');` should be 
`src: url(${webFont.url}) format('${webFont.format}');`

otherwise it's [Object object] vibes

**Comment by bastiaanv** [comment]
@davidhollenbeckx  Sharp! Fixed the problem

**Comment by bukinoshita** [comment]
Can we add this component in the readme.md as well?

**Comment by bastiaanv** [comment]
@bukinoshita Yes ofcourse. Sorry, forgot to do that

**Comment by bukinoshita** [comment]
Can you also add to the new components package, please? https://github.com/resendlabs/react-email/blob/main/packages/components/src/index.ts

**Comment by bastiaanv** [comment]
@bukinoshita Both suggestions are committed now!

**Comment by bukinoshita** [comment]
@bastiaanv Nice, thanks!

**Pull request merged**
