### PR TITLE
fix(client): Support external file imports inside of email components

### PR DESCRIPTION
**Pull request by EyMaddis**
This PR implements a fix for https://github.com/resendlabs/react-email/issues/613.
React Email should now be able to preview files that container imports like `import Theme from '../src/theme'` (sibling directory of `/emails`).

In order to do this, email files are no longer copied over to the `.react-email/emails/` folder but instead files are created which only re-export their default export, like so:

`.react-email/emails/my-template.tsx`:
```jsx
import Mail from '../../my-template.tsx'
export default Mail`
```

Also resolves that static files where not copied over correctly and throwing an error every time.

### CODE REVIEW

**Comment by EyMaddis** [comment]
General feedback:
Firstly: thanks for your great work! I really appreciate this! 👏 
Secondly, I found the contributing experience quite cumbersome as the contribution guide or readme do not explain how to develop in this repository. Through a lot of trial and error, I made it work like so:

```
cd demo
../packages/react-email/node_modules/.bin/ts-node ../packages/react-email/source/index.ts dev
```
which was quick awkward.
(for which I also had to install typescript in the react-email folder).

I assume that you have some monorepo setup somewhere that solves this nicely, but I could not find it.

Maybe you can provide a guide on how to do it properly (or point me to an existing one)

**Comment by EyMaddis** [comment]
I just noticed that this might be a breaking change if people have reusable components inside /emails/, like `/emails/components/Layout.tsx` as it. Such that it will throw a warning:
```warn  - ./emails/components/Layout.tsx
Attempted import error: '../../../emails/components/Layout.tsx' does not contain a default export (imported as 'Mail').

Import trace for requested module:
./emails/components/Layout.tsx
./emails/ lazy ^\.\/.*$ namespace object
./src/app/preview/[slug]/page.tsx
```

I could limit the import to not go over the emails folder recursively. Are folders within the emails directory officially supported?

**Comment by bukinoshita** [comment]
Yeah, this should allow importing components or other files from emails or outside emails.

**Comment by EyMaddis** [comment]
I was working on this branch successfully the last couple of days :)
@bukinoshita should I change this to only load the files directly under /emails/*?
> I could limit the import to not go over the emails folder recursively. Are folders within the emails directory officially supported?

**Comment by bukinoshita** [comment]
Yeah, I think so for now. Because we're only copying the emails/static folders.

**Comment by EyMaddis** [comment]
@bukinoshita I limited it to only use the files from the emails directory directly 🙂
If you could merge it, I would resolve the conflicts with my other PRs.

**Comment by EyMaddis** [comment]
Oh I also noticed something different: I think this also solves automatic reload when changing files. At least I had a lot of problems before working on this branch and now it just works. :)

**Comment by bukinoshita** [comment]
Nice, thanks!

**Comment by bukinoshita** [comment]
@EyMaddis Sorry for the delay, can you check the conflicts?

**Comment by EyMaddis** [comment]
@bukinoshita Done :)

**Comment by kentond18** [comment]
Hey, thanks for your work on this PR. When will this get packaged and released to NPM? 

Says last release was 14 days ago. Just looking to use components with react-email in my project and this has been a roadblock.

**Comment by kleenkanteen** [comment]
This is still on issue on windows 10...

**Pull request merged**
