### PR TITLE
fix(button): Padding behaviour

### PR DESCRIPTION
**Pull request by lordelogos**
### Description
This PR is a fix for #903. It contains the following:
  
- Added logic to handle parsing `padding` from `style` props on `Button` component

- Added tests for utils

### CODE REVIEW

**Comment by bukinoshita** [comment]
@lordelogos Can we remove the support for `pX` and `pY` and rely on the `style` like other properties?

**Comment by shellscape** [comment]
@bukinoshita you were the author of the commit that implemented it https://github.com/resendlabs/react-email/commit/67e054114d0ffca313a9ba4edf2a053ec04c255c. would make sense to revert that first, rather than stall documentation on the current code. at present the documentation doesn't reflect the state of the component, not a good DX there.

**Comment by bukinoshita** [comment]
What happens if the user passes something like this?

```
<Button pY={8} style={{ paddingTop: '10px', paddingBottom: '10px' }}>
```

**Comment by lordelogos** [comment]
> What happens if the user passes something like this?
> 
> ```
> <Button pY={8} style={{ paddingTop: '10px', paddingBottom: '10px' }}>
> ```
`pY` and `pX` no longer exist
The padding values will be picked from the style prop.

in this case padding will be "10px 0 10px 0"

**Review by bukinoshita — APPROVED** [review]

**Review by vcapretz — COMMENTED** [review]
changes look good, but it seems like we would stop supporting `p` props so it looks like a breaking change, we also need to update some examples (I searched for `pX` inside the repo for instance and there's a couple of references to it)

**Comment by lordelogos** [comment]
> changes look good, but it seems like we would stop supporting `p` props so it looks like a breaking change, we also need to update some examples (I searched for `pX` inside the repo for instance and there's a couple of references to it)

Will update the examples in a new PR. 
This is good to go

**Pull request merged**
