### PR TITLE
feat(react-email): Responsive sidebar

### LINKED ISSUE #410: Improve experience on mobile
Although the act of building and testing an email template happens in the browser, people can still access the React Email preview on mobile.

We should make the experience better by addressing the responsive UI issues:

image

image

### PR DESCRIPTION
**Pull request by singhbawan**
This is a WIP for discussion, I will keep adding points as I go through the issue. I want to make the design similar to [main website](https://react.email/docs/introduction) so it stays consistent.

- [x] Page layout 
- [x] Side bar menu always open for screens larger than 1024px
- [x] open/close menu when toggled
- [x] Close menu when item selected
- [x] change order of menu on mobile version 

closes #410

### CODE REVIEW

**Comment by zenorocha** [comment]
I see that all checkboxes are marked, is this ready to review?

**Comment by singhbawan** [comment]
It is ready. I just saw an issue i am working on but it's not related to responsiveness. So i will make a separate issue for it.

**Comment by singhbawan** [comment]
Changes made as requested, ready for review.

**Comment by bukinoshita** [comment]
We need to change the design for this a bit

**Comment by singhbawan** [comment]
Sure thing, can you elaborate what changes you are thinking about?

**Pull request closed without merging**
