### PR TITLE
feat(client): Support `PreviewProps` to avoid default values in components

### PR DESCRIPTION
**Pull request by EyMaddis**
Currently the developer has to use default values in their templates to let them show up in the preview mode of react-email.
However, using default values for an email template is risky::

```jsx
function MyMail({ 
 name = 'Zachary',
 // optional, but will always have a default
 contactReason = 'Hi Zachary, we are sending this because you subscribed to these updates.'
}) { 

  return <Html>
   ...
   {  contactReason && <Text>{ contactReason}</Text> }
   ...
  <Html>

 }

export default MyMail;
```

When rendering the template like so `<MyMail name="Thomas" />` default values that we might have introduced for showing them in the dev preview might "leak" into the production. In this example the `contactReason` would be incorrect.

This PR proposes a solution for this by allowing developers to define a separate set of variables which are used in the preview without having any change to leak into real production code:

```jsx
function MyMail({ 
 name,
  contactReason
}) { ... }

MyMail.PreviewProps = { 
  name: 'Zachary',
  contactReason: 'Hi Zachary, we are sending this because you subscribed to these updates.'
}

export default MyMail;
```

In the future this could additionally show this values in the preview window and even make them editable for testing out different states during the mail design.

### CODE REVIEW

**Comment by bukinoshita** [comment]
Love this @EyMaddis. I remember the default props breaking the `export` command. Can you double check that?

**Comment by EyMaddis** [comment]
If you mean a crash, there actually was one for `stack-overflow-tips` which I now solved.
I also went ahead and slightly improved the spinner experience for the export command. 😜 It will show the current file that is in progress.

```
❯ yarn run export
yarn run v1.22.19
$ email export
✔ Preparing files...

✔ Rendered all files
✔ Copying static files
out
├── airbnb-review.html
├── apple-receipt.html
├── codepen-challengers.html
├── dropbox-reset-password.html
├── github-access-token.html
├── google-play-policy-update.html
├── koala-welcome.html
├── linear-login-code.html
├── nike-receipt.html
├── notion-magic-link.html
├── plaid-verify-identity.html
├── raycast-magic-link.html
├── slack-confirm.html
├── stack-overflow-tips.html
├── static
│   ├── airbnb-logo.png
│   ├── airbnb-review-user.jpg
│   ├── apple-card-icon.png
│   ├── apple-hbo-max-icon.jpeg
│   ├── apple-logo.png
│   ├── apple-wallet.png
│   ├── codepen-challengers.png
│   ├── codepen-cube.png
│   ├── codepen-pro.png
│   ├── dropbox-logo.png
│   ├── github.png
│   ├── google-play-academy.png
│   ├── google-play-chat.png
│   ├── google-play-footer.png
│   ├── google-play-header.png
│   ├── google-play-icon.png
│   ├── google-play-logo.png
│   ├── google-play-pl.png
│   ├── google-play.png
│   ├── koala-logo.png
│   ├── linear-logo.png
│   ├── nike-logo.png
│   ├── nike-phone.png
│   ├── nike-product.png
│   ├── nike-recomendation-1.png
│   ├── nike-recomendation-2.png
│   ├── nike-recomendation-3.png
│   ├── nike-recomendation-4.png
│   ├── notion-logo.png
│   ├── plaid-logo.png
│   ├── raycast-bg.png
│   ├── raycast-logo.png
│   ├── slack-facebook.png
│   ├── slack-linkedin.png
│   ├── slack-logo.png
│   ├── slack-twitter.png
│   ├── stack-overflow-header.png
│   ├── stack-overflow-logo-sm.png
│   ├── stack-overflow-logo.png
│   ├── static
│   │   ├── airbnb-logo.png
│   │   ├── airbnb-review-user.jpg
│   │   ├── apple-card-icon.png
│   │   ├── apple-hbo-max-icon.jpeg
│   │   ├── apple-logo.png
│   │   ├── apple-wallet.png
│   │   ├── codepen-challengers.png
│   │   ├── codepen-cube.png
│   │   ├── codepen-pro.png
│   │   ├── dropbox-logo.png
│   │   ├── github.png
│   │   ├── google-play-academy.png
│   │   ├── google-play-chat.png
│   │   ├── google-play-footer.png
│   │   ├── google-play-header.png
│   │   ├── google-play-icon.png
│   │   ├── google-play-logo.png
│   │   ├── google-play-pl.png
│   │   ├── google-play.png
│   │   ├── koala-logo.png
│   │   ├── linear-logo.png
│   │   ├── nike-logo.png
│   │   ├── nike-phone.png
│   │   ├── nike-product.png
│   │   ├── nike-recomendation-1.png
│   │   ├── nike-recomendation-2.png
│   │   ├── nike-recomendation-3.png
│   │   ├── nike-recomendation-4.png
│   │   ├── notion-logo.png
│   │   ├── plaid-logo.png
│   │   ├── raycast-bg.png
│   │   ├── raycast-logo.png
│   │   ├── slack-facebook.png
│   │   ├── slack-linkedin.png
│   │   ├── slack-logo.png
│   │   ├── slack-twitter.png
│   │   ├── stack-overflow-header.png
│   │   ├── stack-overflow-logo-sm.png
│   │   ├── stack-overflow-logo.png
│   │   ├── stripe-logo.png
│   │   ├── twitch-icon-facebook.png
│   │   ├── twitch-icon-twitter.png
│   │   ├── twitch-logo.png
│   │   ├── vercel-arrow.png
│   │   ├── vercel-logo.png
│   │   ├── vercel-team.png
│   │   ├── vercel-user.png
│   │   ├── yelp-footer.png
│   │   ├── yelp-header.png
│   │   └── yelp-logo.png
│   ├── stripe-logo.png
│   ├── twitch-icon-facebook.png
│   ├── twitch-icon-twitter.png
│   ├── twitch-logo.png
│   ├── vercel-arrow.png
│   ├── vercel-logo.png
│   ├── vercel-team.png
│   ├── vercel-user.png
│   ├── yelp-footer.png
│   ├── yelp-header.png
│   └── yelp-logo.png
├── stripe-welcome.html
├── twitch-reset-password.html
├── vercel-invite-user.html
└── yelp-recent-login.html
✔ Successfully exported emails
✨  Done in 1.82s.
```

**Comment by bukinoshita** [comment]
Got it, can fix the conflicts on this as well? After merging the other one, got some here.

**Comment by EyMaddis** [comment]
@bukinoshita It seems that the lates version does not yet contain this fix. Do you need to release this specifically somehow? Maybe within the dev CLI script?

**Comment by kblauhut** [comment]
> @bukinoshita It seems that the latest version on NPM does not yet contain this fix. Do you need to release this specifically somehow? Maybe within the dev CLI script?

I just set up react-email and would love to have access to this feature too :)

**Comment by jamesmoss** [comment]
Any news on this getting this released on NPM? We really need this feature.

**Comment by shirshendubhowmick** [comment]
Any update on releasing this feature on npm ?

**Pull request merged**
