### PR TITLE
chore(markdown): Upgrade `md-to-react-email` dependency

### PR DESCRIPTION
**Pull request by lordelogos**
**This is a fix for issue #716.**

The problem was JSX was being injected as valid HTML. 
It was an oversight and has been fixed now.

### CODE REVIEW

**Review by zenorocha — COMMENTED** [review]
Is this data-* attribute ID really needed?

**Comment by lordelogos** [comment]
> Is this data-* attribute ID really needed?

I saw it as a convention for all other components. I thought it was for some analytics or rendering optimisation.
If it isn't necessary I will be glad to remove it

**Comment by zenorocha** [comment]
Let's remove it to keep the markup clean

**Comment by lordelogos** [comment]
> Let's remove it to keep the markup clean

They have been removed. 🙂

**Comment by bukinoshita** [comment]
> Let's remove it to keep the markup clean

Actually this should be added to all components.

**Comment by lordelogos** [comment]
> > Let's remove it to keep the markup clean
> 
> Actually this should be added to all components.

Do I add them back? @bukinoshita

**Comment by bukinoshita** [comment]
> > > Let's remove it to keep the markup clean
> > 
> > 
> > Actually this should be added to all components.
> 
> Do I add them back? @bukinoshita

Yup, please. 🙏

**Pull request merged**
