### PR TITLE
fix(section): `Column` inside `Section`

### PR DESCRIPTION
**Pull request by cassiorsfreitas**
This PR implements the issue https://github.com/zenorocha/react-email/issues/309 suggestion in order to correctly manage Column components as children.

```
type ReactEmailChild = {
  type?: {
    displayName?: string;
  }
} & React.ReactNode;

...

const hasTdElement = (child: ReactEmailChild) => {
      return React.isValidElement(child) && (child.type === "td" || child.type.displayName === "Column");
    };
```

### CODE REVIEW

**Review by zenorocha — CHANGES_REQUESTED** [review]
Can you add a test with and without Section as a children element?

**Comment by bukinoshita** [comment]
@cassiorsfreitas I want to merge this, sorry for taking so long. Can you fix the conflicts and let me know so I can merge it?

**Comment by cassiorsfreitas** [comment]
@bukinoshita no worries. done :)

**Comment by bukinoshita** [comment]
Thanks @cassiorsfreitas

**Pull request merged**
