### PR TITLE
fix(container, html): Missing props

### PR DESCRIPTION
**Pull request by leonardorpr**
Hi, guys! what's up?

Adding rest props and ref to the principal div element

### CODE REVIEW

**Review by zenorocha — CHANGES_REQUESTED** [review]
Great catch! I noticed we don't have that on the HTML component too. Do you want to add?

**Comment by leonardorpr** [comment]
> Great catch! I noticed we don't have that on the HTML component too. Do you want to add?

yeah! I'll add 😄

**Comment by leonardorpr** [comment]
Done @zenorocha

**Review by zenorocha — APPROVED** [review]

**Comment by bukinoshita** [comment]
Thanks @leonardorpr !

**Pull request merged**
