### PR TITLE
fix(button): Styles

### LINKED ISSUE #409: Button styles are duplicated
As you can see the styles in the button component are being applied twice hence making it kinda difficult to add margins / borders etc. screenshot

### PR DESCRIPTION
**Pull request by TheBassGuy**

### CODE REVIEW

**Comment by bukinoshita** [comment]
@TheBassGuy Going to take a look on this, IIRC this may cause some padding issues in the button, but let me run some tests before.

**Comment by TheBassGuy** [comment]
sure :D

**Comment by bukinoshita** [comment]
Sorry for taking long, finally got some time to check this locally and run some tests. Looking good

**Comment by gutenye** [comment]
@bukinoshita When will this be released?

**Pull request merged**
